pipeline {
    agent any

    tools {
        maven "MAVEN"
        jdk "JDK"
    }

    stages {
        stage('Initialize'){
            steps{
                echo "PATH = ${M2_HOME}/bin:${PATH}"
                echo "M2_HOME = /usr/local/Cellar/maven/3.8.4/bin/"
            }
        }
        stage('Build') {
            steps {
                dir("/Users/mobven/FirstMavenProject/") {
                //sh 'mvn -B -DskipTests clean test'
                sh 'mvn clean test'
                }

            }
        }
     }
    post {
       always {
          junit(
        allowEmptyResults: true,
        testResults: '*/test-reports/.xml'
      )
      }
   }
}